services:
  polaris:
    image: apache/polaris:latest
    platform: linux/amd64
    ports:
      - "8181:8181"
      - "8182:8182"
    networks:
      - polaris-net
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password
      AWS_REGION: dummy-region
      AWS_ENDPOINT_URL_S3: http://minio:9000
      AWS_ENDPOINT_URL_STS: http://minio:9000
      POLARIS_BOOTSTRAP_CREDENTIALS: default,admin,password
      polaris.realm-context.realms: default
      polaris.features.DROP_WITH_PURGE_ENABLED: "true"
    depends_on:
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8182/q/health"]
      interval: 5s
      timeout: 5s
      retries: 10

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    networks:
      polaris-net:
        aliases:
          - minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: ["server", "/data", "--console-address", ":9001"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio-client:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - polaris-net
    entrypoint: >
      /bin/sh -c "
        mc alias set minio http://minio:9000 admin password;
        mc mb minio/lakehouse;
        mc mb minio/warehouse;
        mc anonymous set public minio/lakehouse;
        mc anonymous set public minio/warehouse;
      "

  spark:
    platform: linux/amd64
    image: alexmerced/spark35nb:latest
    ports:
      - "8080:8080"  # Master Web UI
      - "7077:7077"  # Master Port
      - "8888:8888"  # Jupyter Notebook
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
    container_name: spark
    networks:
      - polaris-net
    depends_on:
      polaris:
        condition: service_healthy
      minio-client:
        condition: service_completed_successfully

networks:
  polaris-net:
    driver: bridge
